### Mod properties
mod.name=Random Item Speedrun
mod.id=random_item_speedrun
mod.version=2.0-beta.1
mod.description=This mod allows you to test your knowledge of the game and your ability to quickly find items

### Publishing
mod.modrinth=le0FiAgt
mod.curseforge=1464099
mod.github=random-item-speedrun

### Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

### Other
net.minecraftforge.gradle.merge-source-sets=true
fabric.loom.disableObfuscation=true
multiloader.enableAdvancedVersionSearch=true
multiloader.editPublishVersions=true
