# Fabric versions see: https://fabricmc.net/develop
# Forge versions see: https://files.minecraftforge.net
# NeoForge versions see: https://neoforged.net
# Extra dependencies see: https://linkie.shedaniel.dev/dependencies

["26.1.2"]
pub-end="latest"
